### ISSUE TITLE
Hosting Option

### ISSUE THREAD

**Issue by DataWookie** [DataWookie/saffeR#3]
Since this is (currently) mostly a "data" package it might make sense to consider alternative hosting options to CRAN. Have a look at [drat](https://journal.r-project.org/archive/2017/RJ-2017-026/RJ-2017-026.pdf). What so you think? Please leave comments below.

**Comment by aidaylanan** [comment]
Sounds interesting! I like the idea of an easily-accessible SA data package, and reading about it, a drat repo seems pretty easy to work with. Would be happy to continue working on this project after the hackathon!

**Comment by DataWookie** [comment]
That'd be great, @aidaylanan! I'm hoping that I'll be able to collaborate with many of you in the future.
